from config.settings.celery import *
from config.settings.jwt import *
from config.settings.cors import *
from config.settings.swagger import *
from config.settings.sessions import *
from config.settings.apps_settings import *
from config.settings.middleware import *
from config.settings.database import *
from config.settings.templates import *
from config.settings.password_validations import *
from config.settings.redis import *
from config.settings.drf import *
from config.settings.languages import *
from config.settings.others import *
from config.settings.local import *
from config.settings.logging import *
from config.settings.websocket import *
from config.settings.elastic_search import *
